name: Build Memos Nightly

on:
#  watch:
#    types: [started]

  schedule:
    # Everyday
    - cron: '0 16 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_MEMOS_USERNAME }}
        password: ${{ secrets.DOCKER_MEMOS_TOKEN }}

    - name: Clone Memos
      run: |
        git clone https://github.com/usememos/memos.git -b main --single-branch memos

    - name: Current date
      run: |
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo ${{ env.TODAY }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "./memos"
        file: ./memos/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          eallion/memos:nightly
          eallion/memos:${{ env.TODAY }}

    - name: Dev mode
      run: |
        cd memos
        sed -i "s/prod/dev/g" ./Dockerfile

    - name: Build and Push Dev
      id: docker_build_dev
      uses: docker/build-push-action@v3
      with:
        context: "./memos"
        file: ./memos/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          eallion/memos:dev
